build:
    environment:
        php:
            version: 7.0.15
filter:
    excluded_paths:
        - public/bolt-public/*
        - public/theme/base-2016/*
checks:
    php:
        code_rating: true
        duplication: true
